apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: prometheus-k8s
  name: prometheus-k8s-token
  namespace: monitoring
type: kubernetes.io/service-account-token
